# Generated by Django 2.0.4 on 2019-08-16 03:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='codeilm', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
