# Generated by Django 2.0.4 on 2019-08-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190816_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.PaymentType'),
        ),
    ]
