# Generated by Django 2.0.4 on 2019-08-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190818_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hash_id',
            new_name='id',
        ),
    ]
