# Generated by Django 2.0.4 on 2018-05-27 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180526_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ramzaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamzaanGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_ip_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ramzaan_requestipinfos', to='mainapp.RequestIpInfo')),
                ('user', models.ForeignKey(help_text='The user in a particular group', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_groupusers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ramzaangroup',
            name='users',
        ),
    ]
