# Generated by Django 2.0.4 on 2018-05-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaangroup',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ramzaangroup',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='A image representing the Community', null=True, upload_to='group_banners/%(app_label)s/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='ramzaangroup',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
