# Generated by Django 2.0.4 on 2018-05-07 02:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0002_auto_20180507_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaangroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='asdf', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
