# Generated by Django 2.0.4 on 2018-05-07 02:55

from django.db import migrations, models
import mainapp.basemodels


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0003_ramzaangroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaangroup',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='A image representing the Community', null=True, upload_to=mainapp.basemodels.upload_to, width_field='width_field'),
        ),
    ]
