# Generated by Django 2.0.4 on 2018-05-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0005_auto_20180507_0301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ramzaanuserprogress',
            unique_together=set(),
        ),
    ]
