# Generated by Django 2.0.4 on 2018-05-12 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ramzaan', '0006_auto_20180508_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamzaanStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_ayat', models.PositiveIntegerField()),
                ('user', models.ForeignKey(help_text="User's status update on a particular group", on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_user_status_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
