# Generated by Django 2.0.4 on 2018-07-06 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0006_auto_20180702_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ramzaangroup',
            options={'permissions': (('owner_of_group', 'Owner of group'),)},
        ),
    ]
