# Generated by Django 2.0.4 on 2018-05-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0007_ramzaanstatusupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ramzaanstatusupdate',
            old_name='on_ayat',
            new_name='on_unit',
        ),
    ]
