# Generated by Django 2.0.4 on 2018-07-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0007_auto_20180706_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamzaanGroupOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, help_text='Whether the group is still private')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the group is still active, set to false when user deletes it')),
                ('show_timer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ramzaangroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ramzaangroup',
            name='is_private',
        ),
        migrations.AddField(
            model_name='ramzaangroupoptions',
            name='group',
            field=models.ForeignKey(help_text='The group for which the group options is entered', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_groupoptions', to='ramzaan.RamzaanGroup'),
        ),
    ]
