# Generated by Django 2.0.4 on 2018-07-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0008_auto_20180706_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaangroupoptions',
            name='group',
            field=models.OneToOneField(help_text='The group for which the group options is entered', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_groupoptions', to='ramzaan.RamzaanGroup'),
        ),
    ]
