# Generated by Django 2.0.4 on 2018-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0008_auto_20180512_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaangroup',
            name='total_units',
            field=models.PositiveIntegerField(help_text='The total number of units in the task'),
        ),
        migrations.AlterField(
            model_name='ramzaanunitdescription',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ramzaanuserprogress',
            name='at_unit',
            field=models.PositiveIntegerField(default=0, help_text='The current state of the user, eg. at chapter 2'),
        ),
    ]
