# Generated by Django 2.0.4 on 2018-07-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0009_auto_20180706_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaangroup',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_groupcreateduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ramzaangroup',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_groupupdateduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ramzaangroup',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='The users who are part of this group', related_name='ramzaan_groupusers', to='ramzaan.RamzaanGroupUser'),
        ),
    ]
