# Generated by Django 2.0.4 on 2018-05-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0009_auto_20180512_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaanstatusupdate',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='ramzaan.RamzaanGroup'),
            preserve_default=False,
        ),
    ]
