# Generated by Django 2.0.4 on 2018-05-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0010_ramzaanstatusupdate_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ramzaanstatusupdate',
            options={'ordering': ['-created_at']},
        ),
    ]
