# Generated by Django 2.0.4 on 2018-07-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0012_auto_20180708_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaanuserprogress',
            name='group',
            field=models.ForeignKey(help_text='The group in which the user make a progress', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_userprogressgroup', to='ramzaan.RamzaanGroup'),
        ),
    ]
