# Generated by Django 2.0.4 on 2018-07-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0014_auto_20180710_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaanunitdescription',
            name='unit_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
