# Generated by Django 2.0.4 on 2018-07-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0015_ramzaanunitdescription_unit_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramzaanuserprogress',
            name='at_unit',
        ),
    ]
