# Generated by Django 2.0.4 on 2018-07-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0017_ramzaanuserprogress_at_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramzaanstatusupdate',
            name='on_unit',
        ),
    ]
