# Generated by Django 2.0.4 on 2018-07-14 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ramzaan', '0019_ramzaanstatusupdate_at_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamzaanGroupUserMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(help_text='The user who sent motivations', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_frommotivation', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group corresponding to which the motivation was sent', on_delete=django.db.models.deletion.CASCADE, related_name='motivation_sent', to='ramzaan.RamzaanGroup')),
                ('to_user', models.ForeignKey(help_text='The user to whom motivation is sent', on_delete=django.db.models.deletion.CASCADE, related_name='ramzaan_tomotivation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
