# Generated by Django 2.0.4 on 2018-07-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0023_ramzaangroup_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramzaangroupcreationrequest',
            name='community',
        ),
        migrations.RemoveField(
            model_name='ramzaangroupcreationrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='RamzaanGroupCreationRequest',
        ),
    ]
