# Generated by Django 2.0.4 on 2018-08-04 12:51

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0024_auto_20180722_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaangroup',
            name='group_hash_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True),
        ),
    ]
