# Generated by Django 2.0.4 on 2018-08-04 12:58

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0025_ramzaangroup_group_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramzaangroup',
            name='group_hash_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, editable=False, min_length=7, null=True, unique=True),
        ),
    ]
