# Generated by Django 2.0.4 on 2018-08-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramzaan', '0026_auto_20180804_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramzaangroupoptions',
            name='extra_content_popup_cta',
            field=models.CharField(blank=True, help_text='The CTA of the modal display button', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramzaangroupoptions',
            name='extra_content_popup_template',
            field=models.CharField(blank=True, help_text='The template of the pop', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramzaangroupoptions',
            name='has_extra_content_popup',
            field=models.BooleanField(default=False, help_text='Has content which needs to be shown in a popup window'),
        ),
    ]
