# Generated by Django 2.0.4 on 2018-05-06 14:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
