# Generated by Django 2.0.4 on 2018-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180526_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendgrid_welcome_email_template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email_id', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
