# Generated by Django 2.0.4 on 2018-07-21 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180721_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_base_url',
            field=models.CharField(default=datetime.datetime(2018, 7, 21, 17, 42, 13, 369392, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
