# Generated by Django 2.0.4 on 2018-07-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_groupcreationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcreationrequest',
            name='request_ip_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_creation_request', to='mainapp.RequestIpInfo'),
        ),
    ]
