# Generated by Django 2.0.4 on 2018-05-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_requestipinfo'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickresponse',
            name='request_ip_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_response', to='mainapp.RequestIpInfo'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='request_ip_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response', to='mainapp.RequestIpInfo'),
        ),
    ]
