# Generated by Django 2.0.4 on 2018-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180515_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackevent',
            name='feedback_url',
            field=models.URLField(default='https://home.com'),
            preserve_default=False,
        ),
    ]
