# Generated by Django 2.0.4 on 2018-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbackevent_feedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackevent',
            name='feedback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
