# Generated by Django 2.0.4 on 2018-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180721_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackevent',
            name='click_response_html',
            field=models.TextField(blank=True, help_text='HTML for the click responses', null=True),
        ),
    ]
