# Generated by Django 2.0.4 on 2018-08-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180722_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
