# Generated by Django 2.0.4 on 2018-05-16 16:36

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20180515_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackevent',
            name='click_response_html',
            field=models.TextField(default='asdf', help_text='HTML for the click responses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackevent',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='A image representing the feedback event', null=True, upload_to=feedback.models.upload_location, width_field='width_field'),
        ),
    ]
