# Generated by Django 2.0.4 on 2018-05-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20180516_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('event', models.ForeignKey(help_text='Form responses of feedback', on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackEvent')),
            ],
        ),
    ]
