# Generated by Django 2.0.4 on 2018-05-17 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
