# Generated by Django 2.0.4 on 2019-03-31 14:40

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='languages',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
