# Generated by Django 2.0.4 on 2019-04-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0003_auto_20190402_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepo',
            name='languages',
        ),
    ]
