# Generated by Django 2.0.4 on 2019-04-06 06:29

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0004_remove_githubrepo_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_data',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
