# Generated by Django 2.0.4 on 2019-04-06 06:29

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0005_tutorial_tutorial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
