# Generated by Django 2.0.4 on 2019-04-14 06:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0007_githubapiresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapiresponse',
            name='headers',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='githubapiresponse',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
