# Generated by Django 2.0.4 on 2019-04-17 05:28

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0009_auto_20190417_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubapiresponse',
            name='request_headers',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
