# Generated by Django 2.0.4 on 2019-04-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0010_githubapiresponse_request_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='repo',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='branch_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='learn_md_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='repository_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
