# Generated by Django 2.0.4 on 2019-04-27 13:54

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0011_auto_20190424_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='hash_id',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
