# Generated by Django 2.0.4 on 2019-05-18 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_groupcreationrequest_request_ip_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lovecodebackend', '0015_tutorial_like_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_ip_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lovecodebackend_requestipinfos', to='mainapp.RequestIpInfo')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='lovecodebackend.Tutorial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tutorial_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tutoriallike',
            options={'ordering': ['-id']},
        ),
    ]
