# Generated by Django 2.0.4 on 2019-05-18 09:32

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0016_auto_20190518_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='view_data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
