# Generated by Django 2.0.4 on 2019-05-24 09:35

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0017_auto_20190518_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='repository_data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
