# Generated by Django 2.0.4 on 2019-06-12 12:26

from django.db import migrations, models
import lovecode.lovecodebackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0018_tutorial_repository_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='rank',
            field=models.FloatField(default=lovecode.lovecodebackend.models.get_default_rank),
        ),
    ]
