# Generated by Django 2.0.4 on 2019-06-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0020_auto_20190612_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-rank']},
        ),
    ]
