# Generated by Django 2.0.4 on 2019-06-13 07:13

from django.db import migrations
import django_mysql.models
import lovecode.lovecodebackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0022_auto_20190613_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='like_data',
            field=django_mysql.models.JSONField(blank=True, default=lovecode.lovecodebackend.models.get_like_data_default),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='view_data',
            field=django_mysql.models.JSONField(blank=True, default=lovecode.lovecodebackend.models.get_view_data_default),
        ),
    ]
