# Generated by Django 2.0.4 on 2019-06-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0026_auto_20190622_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lovecodebackend.TutorialTags'),
        ),
    ]
