# Generated by Django 2.0.4 on 2019-06-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0027_auto_20190623_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tutorials', to=settings.AUTH_USER_MODEL),
        ),
    ]
