# Generated by Django 2.0.4 on 2019-08-24 04:35

from django.db import migrations, models
import lovecode.lovecodebackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0029_tutorial_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='height_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='share_image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='A image representing the tutorial', null=True, upload_to=lovecode.lovecodebackend.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='width_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
