# Generated by Django 2.0.4 on 2018-07-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20180526_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
