# Generated by Django 2.0.4 on 2019-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_connections_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
