# Generated by Django 2.0.4 on 2019-08-10 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lovecodebackend', '0029_tutorial_community'),
        ('usermanagement', '0005_community'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='CodingCommunity',
        ),
    ]
