# Generated by Django 2.0.4 on 2019-08-10 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovecodebackend', '0029_tutorial_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0006_auto_20190810_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingCommunity',
            new_name='Community',
        ),
    ]
