# Generated by Django 2.0.4 on 2019-08-10 15:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_auto_20190810_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
