# Generated by Django 2.0.4 on 2019-08-11 06:04

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_auto_20190810_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
