# Generated by Django 2.0.4 on 2019-08-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_auto_20190811_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
