# Generated by Django 2.0.4 on 2019-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0012_auto_20190822_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_profile_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
