# Generated by Django 2.0.4 on 2019-02-17 05:31

import androidapps.gymapp.gymappbackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymappbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='A image of the exercise', null=True, upload_to=androidapps.gymapp.gymappbackend.models.upload_to, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
