# Generated by Django 2.0.4 on 2019-02-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymappbackend', '0002_auto_20190217_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'permissions': (('owner', 'owner'), ('shared', 'shared'))},
        ),
    ]
