# Generated by Django 2.0.4 on 2019-02-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymappbackend', '0003_auto_20190221_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'permissions': (('owner', 'owner'), ('see_shared', 'see_shared'))},
        ),
    ]
