# Generated by Django 2.0.4 on 2019-02-28 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymappbackend', '0004_auto_20190222_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
