# Generated by Django 2.0.4 on 2018-08-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moocgroup',
            options={'permissions': (('owner_of_group', 'Owner of group'),)},
        ),
    ]
