# Generated by Django 2.0.4 on 2018-08-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('show_employees', models.BooleanField(default=True)),
                ('show_team_page', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_options', to='forteams.Team')),
            ],
        ),
    ]
