# Generated by Django 2.0.4 on 2018-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='displayed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
