# Generated by Django 2.0.4 on 2018-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanager', '0003_unsubscribeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
