# Generated by Django 2.0.4 on 2018-07-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailmanager', '0004_auto_20180701_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
